//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Gameplay : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.gameplay_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.gameplay_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.gameplay_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.gameplay_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.gameplay_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.gameplay_Move;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Turn
        {
            get
            {
                return SteamVR_Actions.gameplay_Turn;
            }
        }
        
        public virtual SteamVR_Action_Boolean Interact
        {
            get
            {
                return SteamVR_Actions.gameplay_Interact;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.gameplay_Menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabLeft
        {
            get
            {
                return SteamVR_Actions.gameplay_GrabLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabRight
        {
            get
            {
                return SteamVR_Actions.gameplay_GrabRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean Sprint
        {
            get
            {
                return SteamVR_Actions.gameplay_Sprint;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.gameplay_Haptic;
            }
        }
    }
}
