//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Pose p_gameplay_Pose;
        
        private static SteamVR_Action_Skeleton p_gameplay_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_gameplay_SkeletonRightHand;
        
        private static SteamVR_Action_Vector2 p_gameplay_Move;
        
        private static SteamVR_Action_Vector2 p_gameplay_Turn;
        
        private static SteamVR_Action_Boolean p_gameplay_Menu;
        
        private static SteamVR_Action_Boolean p_gameplay_GrabLeft;
        
        private static SteamVR_Action_Boolean p_gameplay_GrabRight;
        
        private static SteamVR_Action_Boolean p_gameplay_LeftTrigger;
        
        private static SteamVR_Action_Boolean p_gameplay_RightTrigger;
        
        private static SteamVR_Action_Boolean p_gameplay_CalibrateHeight;
        
        private static SteamVR_Action_Boolean p_gameplay_Sprint;
        
        private static SteamVR_Action_Vibration p_gameplay_Haptic;
        
        public static SteamVR_Action_Pose gameplay_Pose
        {
            get
            {
                return SteamVR_Actions.p_gameplay_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton gameplay_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_gameplay_SkeletonLeftHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton gameplay_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_gameplay_SkeletonRightHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Vector2 gameplay_Move
        {
            get
            {
                return SteamVR_Actions.p_gameplay_Move.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 gameplay_Turn
        {
            get
            {
                return SteamVR_Actions.p_gameplay_Turn.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean gameplay_Menu
        {
            get
            {
                return SteamVR_Actions.p_gameplay_Menu.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean gameplay_GrabLeft
        {
            get
            {
                return SteamVR_Actions.p_gameplay_GrabLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean gameplay_GrabRight
        {
            get
            {
                return SteamVR_Actions.p_gameplay_GrabRight.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean gameplay_LeftTrigger
        {
            get
            {
                return SteamVR_Actions.p_gameplay_LeftTrigger.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean gameplay_RightTrigger
        {
            get
            {
                return SteamVR_Actions.p_gameplay_RightTrigger.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean gameplay_CalibrateHeight
        {
            get
            {
                return SteamVR_Actions.p_gameplay_CalibrateHeight.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean gameplay_Sprint
        {
            get
            {
                return SteamVR_Actions.p_gameplay_Sprint.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration gameplay_Haptic
        {
            get
            {
                return SteamVR_Actions.p_gameplay_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.gameplay_Pose,
                    SteamVR_Actions.gameplay_SkeletonLeftHand,
                    SteamVR_Actions.gameplay_SkeletonRightHand,
                    SteamVR_Actions.gameplay_Move,
                    SteamVR_Actions.gameplay_Turn,
                    SteamVR_Actions.gameplay_Menu,
                    SteamVR_Actions.gameplay_GrabLeft,
                    SteamVR_Actions.gameplay_GrabRight,
                    SteamVR_Actions.gameplay_LeftTrigger,
                    SteamVR_Actions.gameplay_RightTrigger,
                    SteamVR_Actions.gameplay_CalibrateHeight,
                    SteamVR_Actions.gameplay_Sprint,
                    SteamVR_Actions.gameplay_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.gameplay_Pose,
                    SteamVR_Actions.gameplay_SkeletonLeftHand,
                    SteamVR_Actions.gameplay_SkeletonRightHand,
                    SteamVR_Actions.gameplay_Move,
                    SteamVR_Actions.gameplay_Turn,
                    SteamVR_Actions.gameplay_Menu,
                    SteamVR_Actions.gameplay_GrabLeft,
                    SteamVR_Actions.gameplay_GrabRight,
                    SteamVR_Actions.gameplay_LeftTrigger,
                    SteamVR_Actions.gameplay_RightTrigger,
                    SteamVR_Actions.gameplay_CalibrateHeight,
                    SteamVR_Actions.gameplay_Sprint};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.gameplay_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.gameplay_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.gameplay_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.gameplay_Menu,
                    SteamVR_Actions.gameplay_GrabLeft,
                    SteamVR_Actions.gameplay_GrabRight,
                    SteamVR_Actions.gameplay_LeftTrigger,
                    SteamVR_Actions.gameplay_RightTrigger,
                    SteamVR_Actions.gameplay_CalibrateHeight,
                    SteamVR_Actions.gameplay_Sprint};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.gameplay_Move,
                    SteamVR_Actions.gameplay_Turn};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.gameplay_SkeletonLeftHand,
                    SteamVR_Actions.gameplay_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.gameplay_Move,
                    SteamVR_Actions.gameplay_Turn,
                    SteamVR_Actions.gameplay_Menu,
                    SteamVR_Actions.gameplay_GrabLeft,
                    SteamVR_Actions.gameplay_GrabRight,
                    SteamVR_Actions.gameplay_LeftTrigger,
                    SteamVR_Actions.gameplay_RightTrigger,
                    SteamVR_Actions.gameplay_CalibrateHeight,
                    SteamVR_Actions.gameplay_Sprint};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_gameplay_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/Gameplay/in/Pose")));
            SteamVR_Actions.p_gameplay_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/Gameplay/in/SkeletonLeftHand")));
            SteamVR_Actions.p_gameplay_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/Gameplay/in/SkeletonRightHand")));
            SteamVR_Actions.p_gameplay_Move = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/Gameplay/in/Move")));
            SteamVR_Actions.p_gameplay_Turn = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/Gameplay/in/Turn")));
            SteamVR_Actions.p_gameplay_Menu = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Gameplay/in/Menu")));
            SteamVR_Actions.p_gameplay_GrabLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Gameplay/in/GrabLeft")));
            SteamVR_Actions.p_gameplay_GrabRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Gameplay/in/GrabRight")));
            SteamVR_Actions.p_gameplay_LeftTrigger = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Gameplay/in/LeftTrigger")));
            SteamVR_Actions.p_gameplay_RightTrigger = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Gameplay/in/RightTrigger")));
            SteamVR_Actions.p_gameplay_CalibrateHeight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Gameplay/in/CalibrateHeight")));
            SteamVR_Actions.p_gameplay_Sprint = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Gameplay/in/Sprint")));
            SteamVR_Actions.p_gameplay_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/Gameplay/out/Haptic")));
        }
    }
}
